/* SELECT TOP (1000) [Codice Regione]
      ,[Codice dell'Unità territoriale sovracomunale _(valida a fini sta]
      ,[Codice Provincia (Storico)(1)]
      ,[Progressivo del Comune (2)]
      ,[Codice Comune formato alfanumerico]
      ,[Denominazione (Italiana e straniera)]
      ,[Denominazione in italiano]
      ,[Denominazione altra lingua]
      ,[Codice Ripartizione Geografica]
      ,[Ripartizione geografica]
      ,[Denominazione Regione]
      ,[Denominazione dell'Unità territoriale sovracomunale _(valida a f]
      ,[Tipologia di Unità territoriale sovracomunale ]
      ,[Flag Comune capoluogo di provincia/città metropolitana/libero co]
      ,[Sigla automobilistica]
      ,[Codice Comune formato numerico]
      ,[Codice Comune numerico con 110 province (dal 2010 al 2016)]
      ,[Codice Comune numerico con 107 province (dal 2006 al 2009)]
      ,[Codice Comune numerico con 103 province (dal 1995 al 2005)]
      ,[Codice Catastale del comune]
      ,[Codice NUTS1 2010]
      ,[Codice NUTS2 2010 (3) ]
      ,[Codice NUTS3 2010]
      ,[Codice NUTS1 2021]
      ,[Codice NUTS2 2021 (3) ]
      ,[Codice NUTS3 2021]
  FROM [ISTAT2025].[dbo].[Import]

  */ 
  
