apiVersion: v1
kind: apiVersion:v1
kind: Service
metadata:
  name: k8sappswd-service
spec:
  selector:
    app: k8sappswddeployment
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
  # ClusterIP is the default type, exposing the service on a cluster-internal IP
  # Other types include NodePort (exposes on each node's IP) and LoadBalancer (provision an external load balancer)
  # ClusterIP is suitable for internal communication between pods
  # NodePort is useful for exposing services externally, while LoadBalancer is used in cloud environments
  # ClusterIP is the default type, exposing the service on a cluster-internal IP
  